//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductQuotationMVC.EFDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationDetail
    {
        public int QuotationDetailsID { get; set; }
        public int QuotationID { get; set; }
        public int ApproveQuantity { get; set; }
        public int ApproveUserID { get; set; }
        public System.DateTime ApproveDate { get; set; }
        public string Remark { get; set; }
    }
}
